#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.Purchases;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Setup/CostPrices.cshtml")]
    public partial class _Views_Setup_CostPrices_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Setup_CostPrices_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Setup\CostPrices.cshtml"
  
    ViewBag.Title = "Cost Prices";
    Layout = ViewBag.Layout;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    var scrudFactory = new Object();\r\n\r\n    scrudFactory.title = \"C" +
"ost Prices\";\r\n\r\n    scrudFactory.viewAPI = \"/api/views/purchase/item-cost-price-" +
"scrud-view\";\r\n    scrudFactory.viewTableName = \"purchase.item_cost_price_scrud_v" +
"iew\";\r\n\r\n    scrudFactory.formAPI = \"/api/forms/purchase/item-cost-prices\";\r\n   " +
" scrudFactory.formTableName = \"purchase.item_cost_prices\";\r\n\r\n    scrudFactory.e" +
"xcludedColumns = [\"audit_user_id\", \"audit_ts\"];\r\n\r\n    scrudFactory.allowDelete " +
"= true;\r\n    scrudFactory.allowEdit = true;\r\n\r\n    //scrudFactory.live = \"\";\r\n\r\n" +
"    scrudFactory.card = {\r\n        header: \"item\",\r\n        meta: \"unit\",\r\n     " +
"   description: \"price\"        \r\n    };\r\n\r\n    //scrudFactory.layout = [\r\n    //" +
"    {\r\n    //        tab: \"\",\r\n    //        fields: [\r\n    //            [\"\", \"" +
"\"],\r\n    //            [\"\", \"\"],\r\n    //        ]\r\n    //    }\r\n    //];\r\n\r\n    " +
"scrudFactory.keys = [\r\n        {\r\n            property: \"ItemId\",\r\n            u" +
"rl: \'/api/forms/inventory/items/display-fields\',\r\n            data: null,\r\n     " +
"       valueField: \"Key\",\r\n            textField: \"Value\"\r\n        },\r\n        {" +
"\r\n            property: \"UnitId\",\r\n            url: \'/api/forms/inventory/units/" +
"display-fields\',\r\n            data: null,\r\n            valueField: \"Key\",\r\n     " +
"       textField: \"Value\"\r\n        },\r\n        {\r\n            property: \"Supplie" +
"rId\",\r\n            url: \'/api/forms/inventory/suppliers/display-fields\',\r\n      " +
"      data: null,\r\n            valueField: \"Key\",\r\n            textField: \"Value" +
"\"\r\n        }\r\n    ];\r\n\r\n\r\n\r\n    $.get(\'/ScrudFactory/View.html\', function (view)" +
" {\r\n        $.get(\'/ScrudFactory/Form.html\', function (form) {\r\n            $(\"#" +
"ScrudFactoryView\").html(view);\r\n            $(\"#ScrudFactoryForm\").html(form);\r\n" +
"            $.cachedScript(\"/assets/js/scrudfactory-view.js\");\r\n            $.ca" +
"chedScript(\"/assets/js/scrudfactory-form.js\");\r\n        });\r\n    });\r\n</script>\r" +
"\n\r\n<div");

WriteLiteral(" id=\"ScrudFactoryForm\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"ScrudFactoryView\"");

WriteLiteral("></div>");

        }
    }
}
#pragma warning restore 1591
