#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.Purchases;
    
    #line 1 "..\..\Views\Tasks\Order\Index.cshtml"
    using MixERP.Purchases.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Order/Index.cshtml")]
    public partial class _Views_Tasks_Order_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_Order_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Tasks\Order\Index.cshtml"
  
    ViewBag.Title = "Purchase Orders";
    Layout = ViewBag.PurchaseLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 10 "..\..\Views\Tasks\Order\Index.cshtml"
Write(Html.FinancePartialView("Shared/JournalView.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    window.prepareView({\r\n        Title: \"Purchase Orders\",\r\n      " +
"  AddNewText: \"Add New\",\r\n        AddNewUrl: \"/dashboard/purchase/tasks/order/ne" +
"w\",\r\n        ReturnText: \"Return\",\r\n        ReturnUrl: \"javascript:void(0);\",\r\n " +
"       Book: \"Purchase Order\",\r\n        ChecklistUrl: \"/dashboard/purchase/tasks" +
"/order/checklist/{tranId}\",\r\n        AdviceButtons: [\r\n            {\r\n          " +
"      Title: \"View Purchase Order\",\r\n                Href: \"javascript:void(0);\"" +
",\r\n                OnClick: \"showQuotation({tranId});\"\r\n            }\r\n        ]" +
"\r\n    });\r\n\r\n    $(\"#ReturnButton\").click(function () {\r\n        function getSel" +
"ectedItem() {\r\n            const selected = $(\"#JournalView\").find(\"input:checke" +
"d\").first();\r\n\r\n            if (selected.length) {\r\n                const row = " +
"selected.parent().parent().parent();\r\n                const id = row.find(\"td:nt" +
"h-child(3)\").html();\r\n                return parseInt(id);\r\n            };\r\n\r\n  " +
"          return 0;\r\n        };\r\n\r\n        const selected = getSelectedItem();\r\n" +
"        if (selected) {\r\n            const url = \"/dashboard/purchase/tasks/retu" +
"rn/new?TransactionMasterId=\" + selected;\r\n            document.location = url;\r\n" +
"            return;\r\n        };\r\n\r\n        window.displayMessage(\"Please select " +
"an item from the grid.\");\r\n    });\r\n\r\n    function showOrder(tranId) {\r\n        " +
"$(\".advice.modal iframe\").attr(\"src\", \"/dashboard/reports/source/Areas/MixERP.Pu" +
"rchases/Reports/Order.xml?transaction_master_id=\" + tranId);\r\n\r\n        setTimeo" +
"ut(function () {\r\n            $(\".advice.modal\")\r\n                .modal(\'settin" +
"g\', \'transition\', \'horizontal flip\')\r\n                .modal(\"show\");\r\n\r\n       " +
" }, 300);\r\n    };\r\n</script>");

        }
    }
}
#pragma warning restore 1591
