#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.WebsiteBuilder;
    using MixERP.Purchases;
    
    #line 1 "..\..\Views\Tasks\Return\New.cshtml"
    using MixERP.Purchases.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Return/New.cshtml")]
    public partial class _Views_Tasks_Return_New_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_Return_New_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Tasks\Return\New.cshtml"
  
    ViewBag.Title = "Purchase";
    Layout = ViewBag.PurchaseLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 9 "..\..\Views\Tasks\Return\New.cshtml"
Write(Html.PartialView("Shared/ItemList.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<script>\r\n    $(\".page.title\").html(\"Purchase Return\");\r\n    $(\"#CheckoutBu" +
"tton\").unbind(\"click\").bind(\"click\", function () {\r\n\r\n        function request(m" +
"odel) {\r\n            const url = \"/dashboard/purchase/tasks/return/new\";\r\n      " +
"      const data = JSON.stringify(model);\r\n            return window.getAjaxRequ" +
"est(url, \"POST\", data);\r\n        };\r\n\r\n        function getModel() {\r\n          " +
"  function getDetails() {\r\n                const items = $(\"#PurchaseItems .item" +
"\");\r\n                var model = [];\r\n\r\n                $.each(items, function (" +
") {\r\n                    const el = $(this);\r\n                    const itemId =" +
" parseInt(el.attr(\"data-item-id\"));\r\n                    const quantity = parseI" +
"nt(el.find(\"input.quantity\").val());\r\n                    const unitId = parseIn" +
"t(el.find(\"select.unit\").val());\r\n                    const price = parseFloat(e" +
"l.find(\"input.price\").val() || 0);\r\n                    const discount = parseFl" +
"oat(el.find(\"input.discount\").val() || 0);\r\n                    const tax = wind" +
"ow.parseFloat(el.find(\".tax-amount\").html() || 0);\r\n\r\n                    model." +
"push({\r\n                        StoreId: $(\"#StoreSelect\").val(),\r\n             " +
"           ItemId: itemId,\r\n                        Quantity: quantity,\r\n       " +
"                 Tax: tax,\r\n                        UnitId: unitId,\r\n           " +
"             Price: price,\r\n                        Discount: discount\r\n        " +
"            });\r\n                });\r\n\r\n                return model;\r\n         " +
"   };\r\n\r\n            const transactionMasterId = parseInt(window.getQueryStringB" +
"yName(\"TransactionMasterId\") || 0);\r\n            const valueDate = $(\"#ValueDate" +
"InputDate\").datepicker(\"getDate\");\r\n            const bookDate = $(\"#BookDateInp" +
"utDate\").datepicker(\"getDate\");\r\n            const costCenterId = $(\"#CostCenter" +
"Select\").val();\r\n            const referenceNumber = $(\"#ReferenceNumberInputTex" +
"t\").val();\r\n            const statementReference = $(\"#StatementReferenceInputTe" +
"xt\").val();\r\n            const supplierId = $(\"#SupplierSelect\").val();\r\n       " +
"     const priceTypeId = $(\"#PriceTypeSelect\").val();\r\n            const shipper" +
"Id = $(\"#ShipperSelect\").val();\r\n            const storeId = $(\"#StoreSelect\").v" +
"al();\r\n            const details = getDetails();\r\n\r\n            return {\r\n      " +
"          TransactionMasterId: transactionMasterId,\r\n                ValueDate: " +
"valueDate,\r\n                BookDate: bookDate,\r\n                CostCenterId: c" +
"ostCenterId,\r\n                ReferenceNumber: referenceNumber,\r\n               " +
" StatementReference: statementReference,\r\n                SupplierId: supplierId" +
",\r\n                PriceTypeId: priceTypeId,\r\n                ShipperId: shipper" +
"Id,\r\n                StoreId: storeId,\r\n                Details: details\r\n      " +
"      };\r\n        };\r\n\r\n        const model = getModel();\r\n\r\n        if (!model." +
"TransactionMasterId) {\r\n            alert(\"Access is denied.\");\r\n            doc" +
"ument.location = \"/dashboard/purchase/tasks/entry\";\r\n            return;\r\n      " +
"  };\r\n\r\n        if (!model.Details.length) {\r\n            window.displayMessage(" +
"\"Please select an item.\");\r\n            return;\r\n        };\r\n\r\n        const con" +
"firmed = confirm(\"Are you sure\");\r\n\r\n        if (!confirmed) {\r\n            retu" +
"rn;\r\n        };\r\n\r\n\r\n        $(\"#CheckoutButton\").addClass(\"loading\");\r\n\r\n      " +
"  const ajax = request(model);\r\n\r\n        ajax.success(function (response) {\r\n  " +
"          const id = response;\r\n            document.location = \"/dashboard/purc" +
"hase/tasks/return/checklist/\" + id;\r\n        });\r\n\r\n        ajax.fail(function (" +
"xhr) {\r\n            $(\"#CheckoutButton\").removeClass(\"loading\");\r\n            wi" +
"ndow.logAjaxErrorMessage(xhr);\r\n        });\r\n    });\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
