#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.Purchases;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Return/Verification.cshtml")]
    public partial class _Views_Tasks_Return_Verification_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_Return_Verification_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Tasks\Return\Verification.cshtml"
  
    ViewBag.Title = "Purchase Verification";
    Layout = ViewBag.PurchaseLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n<style>\r\n    .modal iframe {\r\n        width: 100%;\r\n        border: none;\r\n    " +
"    height: 700px;\r\n    }\r\n</style>\r\n<script");

WriteLiteral(" src=\"/Scripts/frapid/utilities/form.js\"");

WriteLiteral("></script>\r\n<div");

WriteLiteral(" class=\"ui attached page segment\"");

WriteLiteral(" style=\"min-height: 100%; padding: 3em;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui huge header\"");

WriteLiteral(">Purchase Verification</div>\r\n    <div");

WriteLiteral(" class=\"ui divider\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"ui basic buttons\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(" id=\"VerificationApproveButton\"");

WriteLiteral(">Approve</a>\r\n        <a");

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(" id=\"VerificationRejectButton\"");

WriteLiteral(">Reject</a>\r\n\r\n        <div");

WriteLiteral(" class=\"ui icon top left pointing dropdown basic button\"");

WriteLiteral(" id=\"ExportDropDown\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(">\r\n            <span>\r\n                Export\r\n            </span>\r\n            <" +
"div");

WriteLiteral(" class=\"menu\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"header\"");

WriteLiteral(">\r\n                    Export This Document\r\n                </div>\r\n            " +
"    <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"createDoc();\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file word outline blue icon\"");

WriteLiteral("></i> Export to Doc\r\n                </a>\r\n                <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"createXls();\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file excel outline green icon\"");

WriteLiteral("></i> Export to Excel\r\n                </a>\r\n                <a");

WriteLiteral(" class=\"item\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"createPDF();\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"file pdf outline red icon\"");

WriteLiteral("></i> Export to PDF\r\n                </a>\r\n            </div>\r\n        </div>\r\n  " +
"      <a");

WriteLiteral(" id=\"PrintButton\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" onclick=\"print()\"");

WriteLiteral(" class=\"ui basic button\"");

WriteLiteral(">\r\n            Print\r\n        </a>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"ui stackable form segment\"");

WriteLiteral(" id=\"Annotation\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"eight fields\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"text\"");

WriteLiteral(" placeholder=\"From\"");

WriteLiteral(" id=\"FromInputText\"");

WriteLiteral(" title=\"From\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" class=\"text\"");

WriteLiteral(" placeholder=\"To\"");

WriteLiteral(" id=\"ToInputText\"");

WriteLiteral(" title=\"To\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"TranId\"");

WriteLiteral(" id=\"TranIdInputText\"");

WriteLiteral(" title=\"TranId\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"TranCode\"");

WriteLiteral(" id=\"TranCodeInputText\"");

WriteLiteral(" title=\"TranCode\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"ReferenceNumber\"");

WriteLiteral(" id=\"ReferenceNumberInputText\"");

WriteLiteral(" title=\"ReferenceNumber\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"StatementReference\"");

WriteLiteral(" id=\"StatementReferenceInputText\"");

WriteLiteral(" title=\"StatementReference\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"PostedBy\"");

WriteLiteral(" id=\"PostedByInputText\"");

WriteLiteral(" title=\"PostedBy\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"eight fields\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"Office\"");

WriteLiteral(" id=\"OfficeInputText\"");

WriteLiteral(" title=\"Office\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"Status\"");

WriteLiteral(" id=\"StatusInputText\"");

WriteLiteral(" title=\"Status\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" value=\"Unverified\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"VerifiedBy\"");

WriteLiteral(" id=\"VerifiedByInputText\"");

WriteLiteral(" title=\"VerifiedBy\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"Reason\"");

WriteLiteral(" id=\"ReasonInputText\"");

WriteLiteral(" title=\"Reason\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field hidden\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"UserId\"");

WriteLiteral(" id=\"UserIdInputText\"");

WriteLiteral(" title=\"UserId\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field hidden\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" placeholder=\"OfficeId\"");

WriteLiteral(" id=\"OfficeIdInputText\"");

WriteLiteral(" title=\"OfficeId\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ui green button\"");

WriteLiteral(" id=\"ShowButton\"");

WriteLiteral(">Show</div>\r\n            </div>\r\n        </div>\r\n\r\n\r\n    </div>\r\n\r\n    <table");

WriteLiteral(" id=\"JournalView\"");

WriteLiteral(" class=\"ui table segment\"");

WriteLiteral(@">
        <thead>
            <tr>
                <th>Actions</th>
                <th>Select</th>
                <th>TranId</th>
                <th>TranCode</th>
                <th>Book</th>
                <th>Value Date</th>
                <th>Book Date</th>
                <th>Ref#</th>
                <th>Statement Reference</th>
                <th>Posted By</th>
                <th>Office</th>
                <th>Status</th>
                <th>Verified By</th>
                <th>Verified On</th>
                <th>Reason</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

<div");

WriteLiteral(" id=\"ActionModal\"");

WriteLiteral(" class=\"ui modal\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ui massive red header\"");

WriteLiteral("></div>\r\n    <div");

WriteLiteral(" class=\"ui inverted red content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui form\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ui blue large dividing header\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"field\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"ReasonTextArea\"");

WriteLiteral(">Verification Reason</label>\r\n                <textarea");

WriteLiteral(" id=\"ReasonTextArea\"");

WriteLiteral("></textarea>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"actions\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ui buttons\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"ui red cancel button\"");

WriteLiteral(" value=\"Cancel\"");

WriteLiteral("/>\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"VerifyButton\"");

WriteLiteral(" class=\"ui green ok button\"");

WriteLiteral(" value=\"Verify\"");

WriteLiteral(" title=\"CTRL + RETURN\"");

WriteLiteral("/>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"ui large advice modal\"");

WriteLiteral(">\r\n    <i");

WriteLiteral(" class=\"close icon\"");

WriteLiteral("></i>\r\n    <iframe></iframe>\r\n</div>\r\n\r\n<script>\r\n    function displayTable(targe" +
"t, model) {\r\n        target.find(\"tbody\").html(\"\");\r\n\r\n        function getCell(" +
"text) {\r\n            var cell = $(\"<td />\");\r\n\r\n            cell.text(text || \"\"" +
");\r\n\r\n            return cell;\r\n        };\r\n\r\n        function getActionCell(tra" +
"nId) {\r\n            var cell = $(\"<td />\");\r\n\r\n            var checklistAnchor =" +
" $(\"<a title=\'Checklist Window\'><i class=\'list icon\'></i></a>\");\r\n            ch" +
"ecklistAnchor.attr(\"href\", \"/dashboard/purchase/tasks/return/checklist/\" + tranI" +
"d);\r\n\r\n            var journalAdviceAnchor = $(\"<a title=\'View Journal Advice\'><" +
"i class=\'print icon\'></i></a>\");\r\n            journalAdviceAnchor.attr(\"href\", \"" +
"javascript:void(0);\");\r\n            journalAdviceAnchor.attr(\"onclick\", \"showJou" +
"rnalAdvice(\" + tranId + \");\");\r\n\r\n            var inventoryAdviceAnchor = $(\"<a " +
"title=\'View Purchase Invoice\'><i class=\'zoom icon\'></i></a>\");\r\n            inve" +
"ntoryAdviceAnchor.attr(\"href\", \"javascript:void(0);\");\r\n            inventoryAdv" +
"iceAnchor.attr(\"onclick\", \"showPuchaseInvoice(\" + tranId + \");\");\r\n\r\n\r\n         " +
"   cell.append(checklistAnchor);\r\n            cell.append(journalAdviceAnchor);\r" +
"\n            cell.append(inventoryAdviceAnchor);\r\n            return cell;\r\n    " +
"    };\r\n\r\n        function getSelectionCell() {\r\n            var cell = $(\"<td /" +
">\");\r\n            var checkbox = $(\"<div class=\'ui toggle checkbox\'/>\");\r\n      " +
"      var input = $(\"<input type=\'checkbox\' />\");\r\n            var label = $(\"<l" +
"abel />\");\r\n\r\n            checkbox.append(input);\r\n            checkbox.append(l" +
"abel);\r\n\r\n            cell.append(checkbox);\r\n\r\n            return cell;\r\n      " +
"  };\r\n\r\n        $.each(model,\r\n            function() {\r\n                var ite" +
"m = this;\r\n\r\n                var row = $(\"<tr />\");\r\n\r\n                row.appen" +
"d(getActionCell(item.TransactionMasterId));\r\n                row.append(getSelec" +
"tionCell());\r\n                row.append(getCell(item.TransactionMasterId));\r\n  " +
"              row.append(getCell(item.TransactionCode));\r\n                row.ap" +
"pend(getCell(item.Book));\r\n                row.append(getCell(item.ValueDate));\r" +
"\n                row.append(getCell(item.BookDate));\r\n                row.append" +
"(getCell(item.ReferenceNumber));\r\n                row.append(getCell(item.Statem" +
"entReference));\r\n                row.append(getCell(item.PostedBy));\r\n          " +
"      row.append(getCell(item.Office));\r\n                row.append(getCell(item" +
".Status));\r\n                row.append(getCell(item.VerifiedBy));\r\n             " +
"   row.append(getCell(item.VerifiedOn));\r\n                row.append(getCell(ite" +
"m.Reason));\r\n\r\n                target.find(\"tbody\").append(row);\r\n            })" +
";\r\n    };\r\n\r\n    function processQuery() {\r\n        function getModel() {\r\n     " +
"       var model = window.serializeForm($(\"#Annotation\"));\r\n            model.Bo" +
"ok = \"Purchase\";\r\n\r\n            return model;\r\n        };\r\n\r\n        function di" +
"splayGrid(target) {\r\n            function request(model) {\r\n                var " +
"url = \"/dashboard/finance/tasks/journal/view\";\r\n                var data = JSON." +
"stringify(model);\r\n                return window.getAjaxRequest(url, \"POST\", dat" +
"a);\r\n            };\r\n\r\n            var model = getModel();\r\n\r\n            var aj" +
"ax = request(model);\r\n\r\n            ajax.success(function(response) {\r\n         " +
"       displayTable(target, response);\r\n                target.removeClass(\"load" +
"ing\");\r\n            });\r\n\r\n            ajax.fail(function(xhr) {\r\n              " +
"  alert(JSON.stringify(xhr));\r\n            });\r\n        };\r\n\r\n        var view =" +
" $(\"#JournalView\").addClass(\"loading\");\r\n\r\n        displayGrid(view);\r\n    };\r\n\r" +
"\n    $(\"#ShowButton\")\r\n        .unbind(\"click\")\r\n        .bind(\"click\",\r\n       " +
"     function() {\r\n                processQuery();\r\n            });\r\n\r\n    setTi" +
"meout(function () {\r\n        processQuery();\r\n    }, 1000);\r\n</script>\r\n\r\n<scrip" +
"t>\r\n    var reasonTextArea = $(\"#ReasonTextArea\");\r\n    var journalView = $(\"#Jo" +
"urnalView\");\r\n    var modal = $(\"#ActionModal\");\r\n    var verifyButton = $(\"#Ver" +
"ifyButton\");\r\n    var tranId;\r\n    var approve;\r\n\r\n    function getSelectedItem(" +
") {\r\n        var selected = journalView.find(\"input:checked\").first();\r\n        " +
"\r\n        if (selected.length) {\r\n            var row = selected.parent().parent" +
"().parent();\r\n            var id = row.find(\"td:nth-child(3)\").html();\r\n        " +
"    return parseInt(id);\r\n        };\r\n\r\n        return 0;\r\n    };\r\n\r\n    functio" +
"n showModal() {\r\n        var header = modal.find(\".ui.massive.header\");\r\n       " +
" var subheader = modal.find(\".ui.dividing.header\");\r\n\r\n        header.html(\"Reje" +
"ct Transaction\");\r\n        subheader.html(window.stringFormat(\"TranId: #{0}\", tr" +
"anId));\r\n        header.removeClass(\"green\").addClass(\"red\");\r\n\r\n        if (app" +
"rove) {\r\n            header.html(\"Approve Transaction\");\r\n            header.rem" +
"oveClass(\"red\").addClass(\"green\");\r\n        };\r\n\r\n        modal.modal(\'setting\'," +
" \'closable\', false).modal(\'show\');\r\n    };\r\n\r\n    $(\"#VerificationApproveButton\"" +
").click(function () {\r\n        tranId = getSelectedItem();\r\n\r\n        if (tranId" +
") {\r\n            approve = true;\r\n            showModal();\r\n        };\r\n    });\r" +
"\n\r\n    $(\"#VerificationRejectButton\").click(function () {\r\n        tranId = getS" +
"electedItem();\r\n\r\n        if (tranId) {\r\n            approve = false;\r\n         " +
"   showModal();\r\n        };\r\n    });\r\n\r\n    function removeRow(index, callback) " +
"{\r\n        journalView.find(\"tr\").eq(index + 1).addClass(\"negative\").fadeOut(500" +
", function () {\r\n            $(this).remove();\r\n\r\n            if (typeof (callba" +
"ck) === \"function\") {\r\n                callback();\r\n            };\r\n        });\r" +
"\n    };\r\n\r\n    function hideModal() {\r\n        modal.modal(\"hide\");\r\n    };\r\n\r\n " +
"   verifyButton.click(function () {\r\n        function getModel() {\r\n            " +
"var reason = reasonTextArea.val();\r\n\r\n            return {\r\n                Tran" +
"Id: tranId,\r\n                Reason: reason\r\n            };\r\n        };\r\n\r\n     " +
"   function request(model, type) {\r\n            var url = \"/dashboard/purchase/t" +
"asks/return/verification/\" + type;\r\n            var data = JSON.stringify(model)" +
";\r\n\r\n            return window.getAjaxRequest(url, \"POST\", data);\r\n        }\r\n\r\n" +
"        var model = getModel();\r\n        var type = approve ? \"approve\" : \"rejec" +
"t\";\r\n\r\n        var ajax = request(model, type);\r\n\r\n        ajax.success(function" +
" (response) {\r\n            var cascadingTranId = parseFloat(response);\r\n\r\n      " +
"      if (cascadingTranId) {\r\n                journalView.find(\"tr td:nth-child(" +
"3)\").each(function (i) {\r\n                    var tranId = parseFloat($(this).te" +
"xt() || 0);\r\n\r\n                    if (cascadingTranId === tranId) {\r\n          " +
"              removeRow(i);\r\n                    };\r\n                });\r\n      " +
"      };\r\n\r\n            journalView.find(\"input:checked\").first().parent().paren" +
"t().parent().remove();\r\n            hideModal();\r\n        });\r\n\r\n        ajax.fa" +
"il(function (xhr) {\r\n            window.logAjaxErrorMessage(xhr);\r\n        });\r\n" +
"\r\n        return false;\r\n    });\r\n\r\n    $(document).keyup(function (e) {\r\n      " +
"  if (e.ctrlKey) {\r\n            var rowNumber = e.keyCode - 47;\r\n\r\n            i" +
"f (rowNumber < 10) {\r\n                journalView.find(\"tr\").eq(rowNumber).find(" +
"\"input\").trigger(\'click\');\r\n            };\r\n        };\r\n    });\r\n\r\n    shortcut." +
"add(\"CTRL+K\", function () {\r\n        $(\"#ApproveButton\").trigger(\"click\");\r\n    " +
"});\r\n\r\n    shortcut.add(\"CTRL+RETURN\", function () {\r\n        if (modal.is(\":vis" +
"ible\")) {\r\n            verifyButton.trigger(\"click\");\r\n        };\r\n    });\r\n\r\n  " +
"  shortcut.add(\"CTRL+SHIFT+K\", function () {\r\n        $(\"#VerificationRejectButt" +
"on\").trigger(\"click\");\r\n    });\r\n\r\n    function showPuchaseInvoice(tranId) {\r\n  " +
"      $(\".advice.modal iframe\").attr(\"src\", \"/dashboard/reports/source/Areas/Mix" +
"ERP.Purchases/Reports/Invoice.xml?transaction_master_id=\" + tranId);\r\n\r\n        " +
"setTimeout(function () {\r\n            $(\".advice.modal\")\r\n                .modal" +
"(\'setting\', \'transition\', \'horizontal flip\')\r\n                .modal({\r\n        " +
"            blurring: true\r\n                })\r\n                .modal(\"show\");\r" +
"\n\r\n        }, 300);\r\n    };\r\n    function showJournalAdvice(tranId) {\r\n        $" +
"(\".modal iframe\").attr(\"src\", \"/dashboard/reports/source/Areas/MixERP.Finance/Re" +
"ports/JournalEntry.xml?transaction_master_id=\" + tranId);\r\n\r\n        setTimeout(" +
"function () {\r\n            $(\".advice.modal\")\r\n                .modal(\'setting\'," +
" \'transition\', \'horizontal flip\')\r\n                .modal({\r\n                   " +
" blurring: true\r\n                })\r\n                .modal(\"show\");\r\n\r\n        " +
"}, 300);\r\n    };\r\n\r\n</script>");

        }
    }
}
#pragma warning restore 1591
