#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.Purchases;
    
    #line 1 "..\..\Views\Tasks\Entry\New.cshtml"
    using MixERP.Purchases.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Entry/New.cshtml")]
    public partial class _Views_Tasks_Entry_New_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_Entry_New_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Tasks\Entry\New.cshtml"
  
    ViewBag.Title = "Purchase";
    Layout = ViewBag.PurchaseLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 9 "..\..\Views\Tasks\Entry\New.cshtml"
Write(Html.PartialView("Shared/ItemList.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    window.overrideUrl = \"/dashboard/purchase/tasks/entry\";\r\n\r\n    " +
"$(\"#CheckoutButton\").unbind(\"click\").bind(\"click\", function () {\r\n\r\n        func" +
"tion request(model) {\r\n            const url = \"/dashboard/purchase/tasks/entry/" +
"new\";\r\n            const data = JSON.stringify(model);\r\n            return windo" +
"w.getAjaxRequest(url, \"POST\", data);\r\n        };\r\n\r\n        function getModel() " +
"{\r\n            function getDetails() {\r\n                const items = $(\"#Purcha" +
"seItems .item\");\r\n                var model = [];\r\n\r\n                $.each(item" +
"s, function() {\r\n                    const el = $(this);\r\n                    co" +
"nst itemId = parseInt(el.attr(\"data-item-id\"));\r\n                    const quant" +
"ity = parseInt(el.find(\"input.quantity\").val());\r\n                    const unit" +
"Id = parseInt(el.find(\"select.unit\").val());\r\n                    const price = " +
"parseFloat(el.find(\"input.price\").val() || 0);\r\n                    const discou" +
"nt = parseFloat(el.find(\"input.discount\").val() || 0);\r\n\r\n                    mo" +
"del.push({\r\n                        StoreId: $(\"#StoreSelect\").val(),\r\n         " +
"               ItemId: itemId,\r\n                        Quantity: quantity,\r\n   " +
"                     UnitId: unitId,\r\n                        Price: price,\r\n   " +
"                     Discount: discount\r\n                    });\r\n              " +
"  });\r\n\r\n                return model;\r\n            };\r\n\r\n            const valu" +
"eDate = $(\"#ValueDateInputDate\").datepicker(\"getDate\");\r\n            const bookD" +
"ate = $(\"#BookDateInputDate\").datepicker(\"getDate\");\r\n            const costCent" +
"erId = $(\"#CostCenterSelect\").val();\r\n            const referenceNumber = $(\"#Re" +
"ferenceNumberInputText\").val();\r\n            const statementReference = $(\"#Stat" +
"ementReferenceInputText\").val();\r\n            const supplierId = $(\"#SupplierSel" +
"ect\").val();\r\n            const priceTypeId = $(\"#PriceTypeSelect\").val();\r\n    " +
"        const shipperId = $(\"#ShipperSelect\").val();\r\n            const storeId " +
"= $(\"#StoreSelect\").val();\r\n            const details = getDetails();\r\n\r\n       " +
"     return {\r\n                ValueDate: valueDate,\r\n                BookDate: " +
"bookDate,\r\n                CostCenterId: costCenterId,\r\n                Referenc" +
"eNumber: referenceNumber,\r\n                StatementReference: statementReferenc" +
"e,\r\n                SupplierId: supplierId,\r\n                PriceTypeId: priceT" +
"ypeId,\r\n                ShipperId: shipperId,\r\n                StoreId: storeId," +
"\r\n                Details: details\r\n            };\r\n        };\r\n\r\n        const " +
"model = getModel();\r\n\r\n        if (!model.Details.length) {\r\n            alert(\"" +
"Please select an item.\");\r\n            return;\r\n        };\r\n\r\n        const conf" +
"irmed = confirm(\"Are you sure\");\r\n\r\n        if (!confirmed) {\r\n            retur" +
"n;\r\n        };\r\n\r\n\r\n        $(\"#CheckoutButton\").addClass(\"loading\");\r\n\r\n       " +
" const ajax = request(model);\r\n\r\n        ajax.success(function(response) {\r\n    " +
"        const id = response;\r\n            document.location = `/dashboard/purcha" +
"se/tasks/entry/checklist/${id}`;\r\n        });\r\n\r\n        ajax.fail(function(xhr)" +
" {\r\n            $(\"#CheckoutButton\").removeClass(\"loading\");\r\n            window" +
".logAjaxErrorMessage(xhr);\r\n        });\r\n    });\r\n\r\n</script>");

        }
    }
}
#pragma warning restore 1591
