#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.Mapper.Decorators;
    using Frapid.WebsiteBuilder;
    using MixERP.Purchases;
    
    #line 1 "..\..\Views\Tasks\Entry\Verification.cshtml"
    using MixERP.Purchases.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Entry/Verification.cshtml")]
    public partial class _Views_Tasks_Entry_Verification_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_Entry_Verification_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Tasks\Entry\Verification.cshtml"
  
    ViewBag.Title = "Purchase Entry Verification";
    Layout = ViewBag.PurchaseLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

            
            #line 10 "..\..\Views\Tasks\Entry\Verification.cshtml"
Write(Html.FinancePartialView("Shared/Verification.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    window.prepareVerification({\r\n        Title: \"Purchase Entry Ve" +
"rification\",\r\n        AddNewText: \"Add New\",\r\n        AddNewUrl: \"/dashboard/pur" +
"chase/tasks/entry/new\",\r\n        ReturnText: \"Return\",\r\n        ReturnUrl: \"java" +
"script:void(0);\",\r\n        Book: \"Purchase\",\r\n        ChecklistUrl: \"/dashboard/" +
"purchase/tasks/entry/checklist/{tranId}\",\r\n        AdviceButtons: [\r\n           " +
" {\r\n                Title: \"View Purchase Invoice\",\r\n                Href: \"java" +
"script:void(0);\",\r\n                OnClick: \"showInvoice({tranId});\"\r\n          " +
"  }\r\n        ]\r\n    });\r\n\r\n    $(\"#ReturnButton\").click(function () {\r\n        f" +
"unction getSelectedItem() {\r\n            const selected = $(\"#JournalView\").find" +
"(\"input:checked\").first();\r\n\r\n            if (selected.length) {\r\n              " +
"  const row = selected.parent().parent().parent();\r\n                const id = r" +
"ow.find(\"td:nth-child(3)\").html();\r\n                return parseInt(id);\r\n      " +
"      };\r\n\r\n            return 0;\r\n        };\r\n\r\n        const selected = getSel" +
"ectedItem();\r\n        if (selected) {\r\n            const url = \"/dashboard/purch" +
"ase/tasks/return/new?TransactionMasterId=\" + selected;\r\n            document.loc" +
"ation = url;\r\n            return;\r\n        };\r\n\r\n        window.displayMessage(\"" +
"Please select an item from the grid.\");\r\n    });\r\n\r\n    function showInvoice(tra" +
"nId) {\r\n        $(\".advice.modal iframe\").attr(\"src\", \"/dashboard/reports/source" +
"/Areas/MixERP.Purchases/Reports/Invoice.xml?transaction_master_id=\" + tranId);\r\n" +
"\r\n        setTimeout(function () {\r\n            $(\".advice.modal\")\r\n            " +
"    .modal(\'setting\', \'transition\', \'horizontal flip\')\r\n                .modal(\"" +
"show\");\r\n\r\n        }, 300);\r\n    };\r\n</script>");

        }
    }
}
#pragma warning restore 1591
