#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Frapid.Configuration;
    using Frapid.Dashboard;
    using Frapid.DataAccess;
    using Frapid.DbPolicy;
    using Frapid.Framework;
    using Frapid.i18n;
    using Frapid.Messaging;
    using Frapid.NPoco;
    using Frapid.WebsiteBuilder;
    using MixERP.Purchases;
    
    #line 1 "..\..\Views\Tasks\Quotation\New.cshtml"
    using MixERP.Purchases.Extensions;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Tasks/Quotation/New.cshtml")]
    public partial class _Views_Tasks_Quotation_New_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Tasks_Quotation_New_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Tasks\Quotation\New.cshtml"
  
    ViewBag.Title = "Purchase";
    Layout = ViewBag.PurchaseLayoutPath;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 9 "..\..\Views\Tasks\Quotation\New.cshtml"
Write(Html.PartialView("Shared/ItemList.cshtml", TenantConvention.GetTenant()));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    $(\".page.title\").html(\"Purchase Quotation\");\r\n    $(\"#CheckoutB" +
"utton\").unbind(\"click\").bind(\"click\", function() {\r\n\r\n        function request(m" +
"odel) {\r\n            const url = \"/dashboard/purchase/tasks/entry/new\";\r\n       " +
"     const data = JSON.stringify(model);\r\n            return window.getAjaxReque" +
"st(url, \"POST\", data);\r\n        };\r\n\r\n        function getModel() {\r\n           " +
" function getDetails() {\r\n                const items = $(\"#PurchaseItems .item\"" +
");\r\n                var model = [];\r\n\r\n                $.each(items, function() " +
"{\r\n                    const el = $(this);\r\n                    const itemId = p" +
"arseInt(el.attr(\"data-item-id\"));\r\n                    const quantity = parseInt" +
"(el.find(\"input.quantity\").val());\r\n                    const unitId = parseInt(" +
"el.find(\"select.unit\").val());\r\n                    const price = parseFloat(el." +
"find(\"input.price\").val() || 0);\r\n                    const discount = parseFloa" +
"t(el.find(\"input.discount\").val() || 0);\r\n\r\n                    model.push({\r\n  " +
"                      StoreId: $(\"#StoreSelect\").val(),\r\n                       " +
" ItemId: itemId,\r\n                        Quantity: quantity,\r\n                 " +
"       UnitId: unitId,\r\n                        Price: price,\r\n                 " +
"       Discount: discount\r\n                    });\r\n                });\r\n\r\n     " +
"           return model;\r\n            };\r\n\r\n            const valueDate = $(\"#Va" +
"lueDateInputDate\").datepicker(\"getDate\");\r\n            const bookDate = $(\"#Book" +
"DateInputDate\").datepicker(\"getDate\");\r\n            const costCenterId = $(\"#Cos" +
"tCenterSelect\").val();\r\n            const referenceNumber = $(\"#ReferenceNumberI" +
"nputText\").val();\r\n            const statementReference = $(\"#StatementReference" +
"InputText\").val();\r\n            const supplierId = $(\"#SupplierSelect\").val();\r\n" +
"            const priceTypeId = $(\"#PriceTypeSelect\").val();\r\n            const " +
"shipperId = $(\"#ShipperSelect\").val();\r\n            const storeId = $(\"#StoreSel" +
"ect\").val();\r\n            const details = getDetails();\r\n\r\n            return {\r" +
"\n                ValueDate: valueDate,\r\n                BookDate: bookDate,\r\n   " +
"             CostCenterId: costCenterId,\r\n                ReferenceNumber: refer" +
"enceNumber,\r\n                StatementReference: statementReference,\r\n          " +
"      SupplierId: supplierId,\r\n                PriceTypeId: priceTypeId,\r\n      " +
"          ShipperId: shipperId,\r\n                StoreId: storeId,\r\n            " +
"    Details: details\r\n            };\r\n        };\r\n\r\n        const model = getMod" +
"el();\r\n\r\n        if (!model.Details.length) {\r\n            alert(\"Please select " +
"an item.\");\r\n            return;\r\n        };\r\n\r\n        const confirmed = confir" +
"m(\"Are you sure\");\r\n\r\n        if (!confirmed) {\r\n            return;\r\n        };" +
"\r\n\r\n        alert(\"todo\");\r\n        //$(\"#CheckoutButton\").addClass(\"loading\");\r" +
"\n\r\n        //const ajax = request(model);\r\n\r\n        //ajax.success(function(res" +
"ponse) {\r\n        //    const id = response;\r\n        //    document.location = " +
"`/dashboard/purchase/tasks/entry/checklist/${id}`;\r\n        //});\r\n\r\n        //a" +
"jax.fail(function(xhr) {\r\n        //    $(\"#CheckoutButton\").removeClass(\"loadin" +
"g\");\r\n        //    alert(JSON.stringify(xhr));\r\n        //});\r\n    });\r\n</scrip" +
"t>");

        }
    }
}
#pragma warning restore 1591
